#ifndef C_PP_ENUMS_H
#define C_PP_ENUMS_H

enum PreprocessingTokenKind {
	PREPROCESSING_TOKEN_NONE = 0,
	PREPROCESSING_TOKEN_HEADER_NAME,
	PREPROCESSING_TOKEN_IDENTIFIER,
	PREPROCESSING_TOKEN_PP_NUMBER,
	PREPROCESSING_TOKEN_CHARACTER_CONSTANT,
	PREPROCESSING_TOKEN_STRING_LITERAL,
	PREPROCESSING_TOKEN_PUNCTUATOR,
	PREPROCESSING_TOKEN_ANYTHING,
	PREPROCESSING_TOKEN_NUM,
};

enum ControlLineKind {
	CONTROL_LINE_NONE = 0,
	CONTROL_LINE_INCLUDE,
	CONTROL_LINE_DEFINE,
	CONTROL_LINE_DEFINE_ARGS,
	CONTROL_LINE_DEFINE_VARARGS,
	CONTROL_LINE_DEFINE_ARGS_AND_VARARGS,
	CONTROL_LINE_UNDEF,
	CONTROL_LINE_LINE,
	CONTROL_LINE_ERROR,
	CONTROL_LINE_PRAGMA,
	CONTROL_LINE_EMPTY,
	CONTROL_LINE_NUM,
};

#endif /* C_PP_ENUMS_H */

