#ifndef C_AST_STATEMENT_ENUMS_H
#define C_AST_STATEMENT_ENUMS_H

enum StatementKind {
	STATEMENT_NONE = 0,
	STATEMENT_LABEL,
	STATEMENT_CASE,
	STATEMENT_DEFAULT,
	STATEMENT_COMPOUND,
	STATEMENT_EXPRESSION,
	STATEMENT_IF,
	STATEMENT_SWITCH,
	STAMENENT_WHILE,
	STATEMENT_DO_WHILE,
	STATEMENT_FOR_EXPR,
	STATEMENT_FOR_DECL,
	STATEMENT_GOTO,
	STATEMENT_CONTINUE,
	STATEMENT_BREAK,
	STATEMENT_RETURN,
	STATEMENT_END,
};

enum BlockItemKind {
	BLOCK_ITEM_NONE = 0,
	BLOCK_ITEM_DECLARATION,
	BLOCK_ITEM_STATEMENT,
	BLOCK_ITEM_END,
};

#endif /* C_AST_STATEMENT_ENUMS_H */

