#ifndef C_AST_STATEMENT_ENUMS_H
#define C_AST_STATEMENT_ENUMS_H

enum StatementKind {
	STATEMENT_NONE = 0,
	STATEMENT_LABEL,
	STATEMENT_CASE,
	STATEMENT_DEFAULT,
	STATEMENT_COMPOUND,
	STATEMENT_EXPRESSION,
	STATEMENT_SELECTION,
	STATEMENT_ITERATION,
	STATEMENT_JUMP,
	STATEMENT_NUM,
};

enum BlockItemKind {
	BLOCK_ITEM_NONE = 0,
	BLOCK_ITEM_DECLARATION,
	BLOCK_ITEM_STATEMENT,
	BLOCK_ITEM_NUM,
};

#endif /* C_AST_STATEMENT_ENUMS_H */

