#ifndef C_COMMON_ENUMS_H
#define C_COMMON_ENUMS_H

enum ConstantKind {
	CONSTANT_NONE = 0,
	CONSTANT_INTEGER,
	CONSTANT_FLOATING,
	CONSTANT_ENUMERATION,
	CONSTANT_CHARACTER,
	CONSTANT_NUM,
};

enum ConstantAffix {
	CONSTANT_AFFIX_NONE = 0,
	CONSTANT_AFFIX_U,
	CONSTANT_AFFIX_L,
	CONSTANT_AFFIX_LL,
	CONSTANT_AFFIX_UL,
	CONSTANT_AFFIX_ULL,
	CONSTANT_AFFIX_F,
	CONSTANT_AFFIX_NUM,
};

#endif /* C_COMMON_ENUMS_H */

